name: lab05

on:
 push:
  branches: [main]
  pull_request: [main]

jobs:
 Build: 
  runs-on: ${{ matrix.os }}
  strategy:
   matrix:
    os: [ubuntu-latest]
  steps: 
  - uses: actions/checkout@v3

  - name: lcov_install
    run: |
     sudo apt-get update
     sudo apt-get install -y lcov 

  - name: Build
    run: |
     cmake ${{github.workspace}} -B ${{github.workspace}}/build -DTESTS=ON
     cmake --build ${{github.workspace}}/build

  - name: Test
    run: |
     cd ${{github.workspace}}/build
     ctest

  - name: data_collect
      run: |
        lcov --capture --directory build --output-file cvg.info --rc lcov_branch_coverage=1 --ignore-errors mismatch,inconsistent
        lcov --remove cvg.info '/usr/*' '*/tests/*' '*/build/*' --output-file cvgf.info

  - name: Coveralls
    uses: coverallsapp/github-action@v2
    with:
        path-to-lcov: cvgf.info
